---
title: "The Brosey Farm 2023 Crop Report: `r params$crop`"
author: "*The Brosey Farm Analytics Team*"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  html_document:
    toc: true
    toc_depth: 2
    number_sections: true
    css: BF_crop_report_styles.css
params:
    crop: kale- lacinato
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.align = 'left')
```

```{r filter_data `r params$crop`, include = FALSE}
##load required R packages##
  pacman::p_load(tidyverse, readr, stringr, visdat, skimr, DT, esquisse, datamods, lubridate, fasttime, googlesheets4)

##import 2023 bf crop data##
  #bf_2023 <- read_csv("Brosey Farming - data_2023.csv")
  bf_2023 <- read_sheet("https://docs.google.com/spreadsheets/d/1lXsVEpM5iNZrNqlap8JHbxeIxeXF_C3s--FMrx_Inc8/edit#gid=707201855", sheet = "data_2023")
  bf_2023_kale <- bf_2023 %>% filter(crop == params$crop)
  #str(bf_2023_kale)
```

# Descriptive statistics for crop: `r params$crop`
```{r exploratory_analysis, echo=FALSE}
  bf_2023_kale <- bf_2023_kale %>% 
    mutate(sow_no_seed_tot= sow_no_cellrowhill* sow_no_seed_per, 
           sow_no_germ_pct= (sow_no_germ_per/sow_no_seed_per)*100,
           sow_to_transp_days= difftime(transp_date_1, sow_date, units = "days"),
           transp_harden_days= difftime(transp_harden_date_end, transp_harden_date_srt, units = "days"))
  bf_2023_kale %>% count(crop, sow_date, wt= sow_no_seed_tot)
```
## Seed sown and germinations
  
## Transplanting dates and media

# Pest management for crop: `r params$crop` 